### ISSUE TITLE
Improvements TODO

### ISSUE THREAD

**Issue by alfonsograziano** [alfonsograziano/italian-auctions-alert#1]
I'll list here a few improvements that can be applied (in case someone wants to contribute and open a PR): 

- [ ] - Replace Mongo with DynamoDB Serverless (the price should still be almost 0 as the amount of read and writes is very low)
- [ ] - Create a IaC file to configure all the resources (both Terraform or Cloudformation should do the trick) 
- [ ] - Allow research with multiple filters at once. Let's assume I'm interested in auctions in my city and Milan
- [ ] - Add tests (what tests? lol)
- [ ] - Trigger an alert if the request to PVP fails  
- [ ] - Somehow make retrieving the filters information less painful and more user-friendly
- [ ] Build a SaaS on top of this super simple script (kind of a joke, but you know...)
